# Generated by Django 5.0.6 on 2024-05-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("_blogs", "0001_initial"),
        ("_projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogs",
            name="related_projects",
            field=models.ManyToManyField(to="_projects.projects"),
        ),
    ]
