# Generated by Django 5.0.6 on 2024-05-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("_blogs", "0002_initial"),
        ("_links", "0001_initial"),
        ("_projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogs",
            name="links",
            field=models.ManyToManyField(blank=True, to="_links.links"),
        ),
        migrations.AlterField(
            model_name="blogs",
            name="related_projects",
            field=models.ManyToManyField(blank=True, to="_projects.projects"),
        ),
    ]
