# Generated by Django 5.0.6 on 2024-05-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeedBack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=250, verbose_name="Full Name"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("subject", models.CharField(max_length=350, verbose_name="Subject")),
                ("message", models.TextField(verbose_name="Message")),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Feed Back",
                "verbose_name_plural": "Feed Back",
                "db_table": "Feed Back",
            },
        ),
    ]
