# Generated by Django 5.0.6 on 2024-05-09 16:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("_profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tel",
            options={"verbose_name": "Tel", "verbose_name_plural": "Tel"},
        ),
    ]
