# Generated by Django 5.0.6 on 2024-05-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("_profile", "0004_remove_profile_files_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="about_pic",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="uploads/_profile/images",
                verbose_name="About page picture",
            ),
        ),
    ]
