# Generated by Django 5.0.6 on 2024-05-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("_profile", "0006_alter_services_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="mission_statement",
            field=models.TextField(
                blank=True, null=True, verbose_name="Mission Statement"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="vision_statement",
            field=models.TextField(
                blank=True, null=True, verbose_name="Vision Statement"
            ),
        ),
    ]
