# Generated by Django 5.0.6 on 2024-05-09 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("_profile", "0007_profile_mission_statement_profile_vision_statement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="mission_statement",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="vision_statement",
        ),
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=450)),
                ("statement", models.TextField(verbose_name="Statement")),
                (
                    "profile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mission",
                        to="_profile.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mission",
                "verbose_name_plural": "Mission",
                "db_table": "Mission",
            },
        ),
        migrations.CreateModel(
            name="Vision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=450)),
                ("statement", models.TextField(verbose_name="Statement")),
                (
                    "profile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Vision",
                        to="_profile.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vision",
                "verbose_name_plural": "Vision",
                "db_table": "Vision",
            },
        ),
    ]
