# Generated by Django 5.0.6 on 2024-05-09 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("_profile", "0008_remove_profile_mission_statement_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mission",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="vision",
            name="profile",
        ),
        migrations.AddField(
            model_name="profile",
            name="mission",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="_profile.vision",
            ),
        ),
    ]
