# Generated by Django 5.0.6 on 2024-05-09 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("_profile", "0009_remove_mission_profile_remove_vision_profile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="vision",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="_profile.vision",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="mission",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="_profile.mission",
            ),
        ),
    ]
