# Generated by Django 5.0.6 on 2024-05-09 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("_profile", "0010_profile_vision_alter_profile_mission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="mission",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mission",
                to="_profile.mission",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="vision",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vision",
                to="_profile.vision",
            ),
        ),
    ]
