# Generated by Django 5.0.6 on 2024-05-21 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("_profile", "0012_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skills",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="skill",
                to="_profile.profile",
            ),
        ),
    ]
