# Generated by Django 5.0.6 on 2024-06-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_profile', '0014_alter_skills_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='file',
        ),
        migrations.AddField(
            model_name='files',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='_profile/Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='files',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='_profile/files', verbose_name='File'),
        ),
        migrations.AddField(
            model_name='files',
            name='title',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about_pic',
            field=models.ImageField(blank=True, null=True, upload_to='_profile/images', verbose_name='About page picture'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='_profile/images', verbose_name='Profile picture'),
        ),
        migrations.AlterField(
            model_name='services',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='_profile/icons', verbose_name='Icon'),
        ),
    ]
