# Generated by Django 5.0.6 on 2024-05-09 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("_blogs", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Links",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Link")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "related_blog",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blogs",
                        to="_blogs.blogs",
                    ),
                ),
            ],
            options={
                "verbose_name": "Links",
                "verbose_name_plural": "Links",
                "db_table": "Links",
            },
        ),
    ]
