# Generated by Django 5.0.6 on 2024-05-09 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("_links", "0001_initial"),
        ("_profile", "0001_initial"),
        ("_projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="links",
            name="related_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profile",
                to="_profile.profile",
            ),
        ),
        migrations.AddField(
            model_name="links",
            name="related_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="_projects.projects",
            ),
        ),
    ]
