# Generated by Django 5.0.6 on 2024-05-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("_links", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="links",
            name="url",
            field=models.CharField(default=1, max_length=500, verbose_name="Url"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="links",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Name"),
        ),
    ]
