# Generated by Django 5.0.6 on 2024-05-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("_blogs", "0001_initial"),
        ("_categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="uploads/_projects/images"
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("text", models.TextField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="projects", to="_categories.categories"
                    ),
                ),
                ("related_blogs", models.ManyToManyField(to="_blogs.blogs")),
            ],
            options={
                "verbose_name": "Projects",
                "verbose_name_plural": "Projects",
                "db_table": "Projects",
            },
        ),
    ]
