# Generated by Django 5.0.6 on 2024-05-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("_blogs", "0003_blogs_links_alter_blogs_related_projects"),
        ("_categories", "0001_initial"),
        ("_links", "0002_initial"),
        ("_projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="links",
            field=models.ManyToManyField(blank=True, to="_links.links"),
        ),
        migrations.AlterField(
            model_name="projects",
            name="categories",
            field=models.ManyToManyField(to="_categories.categories"),
        ),
        migrations.AlterField(
            model_name="projects",
            name="related_blogs",
            field=models.ManyToManyField(blank=True, to="_blogs.blogs"),
        ),
    ]
