# Generated by Django 5.0.6 on 2024-06-01 23:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("_categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categories",
            options={
                "ordering": ("-id",),
                "verbose_name": "Categories",
                "verbose_name_plural": "Categories",
            },
        ),
    ]
